//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MNAIS.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MNAISResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MNAISResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MNAIS.Resources.MNAISResources", typeof(MNAISResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % Extreme.
        /// </summary>
        public static string @__Extreme {
            get {
                return ResourceManager.GetString("% Extreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.5 %.
        /// </summary>
        public static string _7_5__ {
            get {
                return ResourceManager.GetString("7.5 %", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 70 %.
        /// </summary>
        public static string _70__ {
            get {
                return ResourceManager.GetString("70 %", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 80 %.
        /// </summary>
        public static string _80__ {
            get {
                return ResourceManager.GetString("80 %", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 90 %.
        /// </summary>
        public static string _90__ {
            get {
                return ResourceManager.GetString("90 %", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 95 %.
        /// </summary>
        public static string _95__ {
            get {
                return ResourceManager.GetString("95 %", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99 %.
        /// </summary>
        public static string _99__ {
            get {
                return ResourceManager.GetString("99 %", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acres.
        /// </summary>
        public static string Acres {
            get {
                return ResourceManager.GetString("Acres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Crops.
        /// </summary>
        public static string All_Crops {
            get {
                return ResourceManager.GetString("All Crops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alpha.
        /// </summary>
        public static string Alpha {
            get {
                return ResourceManager.GetString("Alpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aman Paddy.
        /// </summary>
        public static string Aman_Paddy {
            get {
                return ResourceManager.GetString("Aman Paddy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Andaman and Nicobar Islands.
        /// </summary>
        public static string Andaman_and_Nicobar_Islands {
            get {
                return ResourceManager.GetString("Andaman and Nicobar Islands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Andhra Pradesh.
        /// </summary>
        public static string Andhra_Pradesh {
            get {
                return ResourceManager.GetString("Andhra Pradesh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anise.
        /// </summary>
        public static string Anise {
            get {
                return ResourceManager.GetString("Anise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apple.
        /// </summary>
        public static string Apple {
            get {
                return ResourceManager.GetString("Apple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arecanut.
        /// </summary>
        public static string Arecanut {
            get {
                return ResourceManager.GetString("Arecanut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arhar.
        /// </summary>
        public static string Arhar {
            get {
                return ResourceManager.GetString("Arhar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arunachal Pradesh.
        /// </summary>
        public static string Arunachal_Pradesh {
            get {
                return ResourceManager.GetString("Arunachal Pradesh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assam.
        /// </summary>
        public static string Assam {
            get {
                return ResourceManager.GetString("Assam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bajra.
        /// </summary>
        public static string Bajra {
            get {
                return ResourceManager.GetString("Bajra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banana.
        /// </summary>
        public static string Banana {
            get {
                return ResourceManager.GetString("Banana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barley.
        /// </summary>
        public static string Barley {
            get {
                return ResourceManager.GetString("Barley", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beta.
        /// </summary>
        public static string Beta {
            get {
                return ResourceManager.GetString("Beta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bhindi.
        /// </summary>
        public static string Bhindi {
            get {
                return ResourceManager.GetString("Bhindi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bihar.
        /// </summary>
        public static string Bihar {
            get {
                return ResourceManager.GetString("Bihar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boro Paddy.
        /// </summary>
        public static string Boro_Paddy {
            get {
                return ResourceManager.GetString("Boro Paddy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brinjal.
        /// </summary>
        public static string Brinjal {
            get {
                return ResourceManager.GetString("Brinjal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cabbage.
        /// </summary>
        public static string Cabbage {
            get {
                return ResourceManager.GetString("Cabbage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculated.
        /// </summary>
        public static string Calculated {
            get {
                return ResourceManager.GetString("Calculated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cardamom.
        /// </summary>
        public static string Cardamom {
            get {
                return ResourceManager.GetString("Cardamom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cashewnut.
        /// </summary>
        public static string Cashewnut {
            get {
                return ResourceManager.GetString("Cashewnut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Castor Oil seed.
        /// </summary>
        public static string Castor_Oil_seed {
            get {
                return ResourceManager.GetString("Castor Oil seed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cauliflower.
        /// </summary>
        public static string Cauliflower {
            get {
                return ResourceManager.GetString("Cauliflower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chandigarh.
        /// </summary>
        public static string Chandigarh {
            get {
                return ResourceManager.GetString("Chandigarh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chhattisgarh.
        /// </summary>
        public static string Chhattisgarh {
            get {
                return ResourceManager.GetString("Chhattisgarh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chick Peas.
        /// </summary>
        public static string Chick_Peas {
            get {
                return ResourceManager.GetString("Chick Peas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chillies.
        /// </summary>
        public static string Chillies {
            get {
                return ResourceManager.GetString("Chillies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Option.
        /// </summary>
        public static string ChooseOption {
            get {
                return ResourceManager.GetString("ChooseOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cocoa.
        /// </summary>
        public static string Cocoa {
            get {
                return ResourceManager.GetString("Cocoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coconut.
        /// </summary>
        public static string Coconut {
            get {
                return ResourceManager.GetString("Coconut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coriander.
        /// </summary>
        public static string Coriander {
            get {
                return ResourceManager.GetString("Coriander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correlation.
        /// </summary>
        public static string Correlation {
            get {
                return ResourceManager.GetString("Correlation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cotton.
        /// </summary>
        public static string Cotton {
            get {
                return ResourceManager.GetString("Cotton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cotton Irrigated.
        /// </summary>
        public static string Cotton_Irrigated {
            get {
                return ResourceManager.GetString("Cotton Irrigated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cotton Rainfed.
        /// </summary>
        public static string Cotton_Rainfed {
            get {
                return ResourceManager.GetString("Cotton Rainfed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cowpea.
        /// </summary>
        public static string Cowpea {
            get {
                return ResourceManager.GetString("Cowpea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cumin.
        /// </summary>
        public static string Cumin {
            get {
                return ResourceManager.GetString("Cumin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dadra and Nagar Haveli.
        /// </summary>
        public static string Dadra_and_Nagar_Haveli {
            get {
                return ResourceManager.GetString("Dadra and Nagar Haveli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daman and Diu.
        /// </summary>
        public static string Daman_and_Diu {
            get {
                return ResourceManager.GetString("Daman and Diu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal.
        /// </summary>
        public static string Decimal {
            get {
                return ResourceManager.GetString("Decimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deductible.
        /// </summary>
        public static string Deductible {
            get {
                return ResourceManager.GetString("Deductible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delhi.
        /// </summary>
        public static string Delhi {
            get {
                return ResourceManager.GetString("Delhi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detrend None.
        /// </summary>
        public static string Detrend_None {
            get {
                return ResourceManager.GetString("Detrend None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DetrendAll.
        /// </summary>
        public static string DetrendAll {
            get {
                return ResourceManager.GetString("DetrendAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detrended.
        /// </summary>
        public static string Detrended {
            get {
                return ResourceManager.GetString("Detrended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dry Beans.
        /// </summary>
        public static string Dry_Beans {
            get {
                return ResourceManager.GetString("Dry Beans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluded.
        /// </summary>
        public static string Excluded {
            get {
                return ResourceManager.GetString("Excluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fennel.
        /// </summary>
        public static string Fennel {
            get {
                return ResourceManager.GetString("Fennel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fenugreek (Methi).
        /// </summary>
        public static string Fenugreek__Methi_ {
            get {
                return ResourceManager.GetString("Fenugreek (Methi)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filled.
        /// </summary>
        public static string Filled {
            get {
                return ResourceManager.GetString("Filled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 500.
        /// </summary>
        public static string FiveHundred {
            get {
                return ResourceManager.GetString("FiveHundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Franchise.
        /// </summary>
        public static string Franchise {
            get {
                return ResourceManager.GetString("Franchise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garlic.
        /// </summary>
        public static string Garlic {
            get {
                return ResourceManager.GetString("Garlic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ginger.
        /// </summary>
        public static string Ginger {
            get {
                return ResourceManager.GetString("Ginger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goa.
        /// </summary>
        public static string Goa {
            get {
                return ResourceManager.GetString("Goa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gourds.
        /// </summary>
        public static string Gourds {
            get {
                return ResourceManager.GetString("Gourds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gram.
        /// </summary>
        public static string Gram {
            get {
                return ResourceManager.GetString("Gram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grapes.
        /// </summary>
        public static string Grapes {
            get {
                return ResourceManager.GetString("Grapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green Peas.
        /// </summary>
        public static string Green_Peas {
            get {
                return ResourceManager.GetString("Green Peas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gross Premium.
        /// </summary>
        public static string Gross_Premium {
            get {
                return ResourceManager.GetString("Gross Premium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groundnut.
        /// </summary>
        public static string Groundnut {
            get {
                return ResourceManager.GetString("Groundnut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guar.
        /// </summary>
        public static string Guar {
            get {
                return ResourceManager.GetString("Guar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guava.
        /// </summary>
        public static string Guava {
            get {
                return ResourceManager.GetString("Guava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gujarat.
        /// </summary>
        public static string Gujarat {
            get {
                return ResourceManager.GetString("Gujarat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha.
        /// </summary>
        public static string Ha {
            get {
                return ResourceManager.GetString("Ha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haryana.
        /// </summary>
        public static string Haryana {
            get {
                return ResourceManager.GetString("Haryana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Himachal Pradesh.
        /// </summary>
        public static string Himachal_Pradesh {
            get {
                return ResourceManager.GetString("Himachal Pradesh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historical.
        /// </summary>
        public static string Historical {
            get {
                return ResourceManager.GetString("Historical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historical Maximum.
        /// </summary>
        public static string Historical_Maximum {
            get {
                return ResourceManager.GetString("Historical Maximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horse Gram.
        /// </summary>
        public static string Horse_Gram {
            get {
                return ResourceManager.GetString("Horse Gram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Included.
        /// </summary>
        public static string Included {
            get {
                return ResourceManager.GetString("Included", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isabgol.
        /// </summary>
        public static string Isabgol {
            get {
                return ResourceManager.GetString("Isabgol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jackfruit.
        /// </summary>
        public static string Jackfruit {
            get {
                return ResourceManager.GetString("Jackfruit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jammu and Kashmir.
        /// </summary>
        public static string Jammu_and_Kashmir {
            get {
                return ResourceManager.GetString("Jammu and Kashmir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jharkhand.
        /// </summary>
        public static string Jharkhand {
            get {
                return ResourceManager.GetString("Jharkhand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jowar.
        /// </summary>
        public static string Jowar {
            get {
                return ResourceManager.GetString("Jowar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jute.
        /// </summary>
        public static string Jute {
            get {
                return ResourceManager.GetString("Jute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karnataka.
        /// </summary>
        public static string Karnataka {
            get {
                return ResourceManager.GetString("Karnataka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keenu.
        /// </summary>
        public static string Keenu {
            get {
                return ResourceManager.GetString("Keenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kerala.
        /// </summary>
        public static string Kerala {
            get {
                return ResourceManager.GetString("Kerala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kharif.
        /// </summary>
        public static string Kharif {
            get {
                return ResourceManager.GetString("Kharif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilogram.
        /// </summary>
        public static string Kilogram {
            get {
                return ResourceManager.GetString("Kilogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilogram/Ha.
        /// </summary>
        public static string KilogramHa {
            get {
                return ResourceManager.GetString("KilogramHa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lakshadweep.
        /// </summary>
        public static string Lakshadweep {
            get {
                return ResourceManager.GetString("Lakshadweep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lentil.
        /// </summary>
        public static string Lentil {
            get {
                return ResourceManager.GetString("Lentil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lime/Lemon.
        /// </summary>
        public static string Lime_Lemon {
            get {
                return ResourceManager.GetString("Lime/Lemon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linseed.
        /// </summary>
        public static string Linseed {
            get {
                return ResourceManager.GetString("Linseed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Litchi.
        /// </summary>
        public static string Litchi {
            get {
                return ResourceManager.GetString("Litchi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Normal.
        /// </summary>
        public static string Log_Normal {
            get {
                return ResourceManager.GetString("Log Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Madhya Pradesh.
        /// </summary>
        public static string Madhya_Pradesh {
            get {
                return ResourceManager.GetString("Madhya Pradesh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maharashtra.
        /// </summary>
        public static string Maharashtra {
            get {
                return ResourceManager.GetString("Maharashtra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maize.
        /// </summary>
        public static string Maize {
            get {
                return ResourceManager.GetString("Maize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mango.
        /// </summary>
        public static string Mango {
            get {
                return ResourceManager.GetString("Mango", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manipur.
        /// </summary>
        public static string Manipur {
            get {
                return ResourceManager.GetString("Manipur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masoor.
        /// </summary>
        public static string Masoor {
            get {
                return ResourceManager.GetString("Masoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum.
        /// </summary>
        public static string Maximum {
            get {
                return ResourceManager.GetString("Maximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mean Loss Ratio.
        /// </summary>
        public static string Mean_Loss_Ratio {
            get {
                return ResourceManager.GetString("Mean Loss Ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meghalaya.
        /// </summary>
        public static string Meghalaya {
            get {
                return ResourceManager.GetString("Meghalaya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Millets (other than Maize).
        /// </summary>
        public static string Millets__other_than_Maize_ {
            get {
                return ResourceManager.GetString("Millets (other than Maize)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mizoram.
        /// </summary>
        public static string Mizoram {
            get {
                return ResourceManager.GetString("Mizoram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moong.
        /// </summary>
        public static string Moong {
            get {
                return ResourceManager.GetString("Moong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mosambi.
        /// </summary>
        public static string Mosambi {
            get {
                return ResourceManager.GetString("Mosambi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moth.
        /// </summary>
        public static string Moth {
            get {
                return ResourceManager.GetString("Moth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving Average.
        /// </summary>
        public static string Moving_Average {
            get {
                return ResourceManager.GetString("Moving Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mustard.
        /// </summary>
        public static string Mustard {
            get {
                return ResourceManager.GetString("Mustard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nagaland.
        /// </summary>
        public static string Nagaland {
            get {
                return ResourceManager.GetString("Nagaland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Filled.
        /// </summary>
        public static string Not_Filled {
            get {
                return ResourceManager.GetString("Not Filled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nutmeg And Mace.
        /// </summary>
        public static string Nutmeg_And_Mace {
            get {
                return ResourceManager.GetString("Nutmeg And Mace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odisha.
        /// </summary>
        public static string Odisha {
            get {
                return ResourceManager.GetString("Odisha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1000.
        /// </summary>
        public static string OneThousand {
            get {
                return ResourceManager.GetString("OneThousand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onion.
        /// </summary>
        public static string Onion {
            get {
                return ResourceManager.GetString("Onion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orange.
        /// </summary>
        public static string Orange {
            get {
                return ResourceManager.GetString("Orange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Millets.
        /// </summary>
        public static string Other_Millets {
            get {
                return ResourceManager.GetString("Other Millets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        public static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paddy.
        /// </summary>
        public static string Paddy {
            get {
                return ResourceManager.GetString("Paddy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paddy II.
        /// </summary>
        public static string Paddy_II {
            get {
                return ResourceManager.GetString("Paddy II", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Papaya.
        /// </summary>
        public static string Papaya {
            get {
                return ResourceManager.GetString("Papaya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payout Correlation.
        /// </summary>
        public static string Payout_Correlation {
            get {
                return ResourceManager.GetString("Payout Correlation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peas.
        /// </summary>
        public static string Peas {
            get {
                return ResourceManager.GetString("Peas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peppers.
        /// </summary>
        public static string Peppers {
            get {
                return ResourceManager.GetString("Peppers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage.
        /// </summary>
        public static string Percentage {
            get {
                return ResourceManager.GetString("Percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pigeon Peas.
        /// </summary>
        public static string Pigeon_Peas {
            get {
                return ResourceManager.GetString("Pigeon Peas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pine Apple.
        /// </summary>
        public static string Pine_Apple {
            get {
                return ResourceManager.GetString("Pine Apple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pomegranate.
        /// </summary>
        public static string Pomegranate {
            get {
                return ResourceManager.GetString("Pomegranate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potato.
        /// </summary>
        public static string Potato {
            get {
                return ResourceManager.GetString("Potato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Present.
        /// </summary>
        public static string Present {
            get {
                return ResourceManager.GetString("Present", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production.
        /// </summary>
        public static string Production {
            get {
                return ResourceManager.GetString("Production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proportional.
        /// </summary>
        public static string Proportional {
            get {
                return ResourceManager.GetString("Proportional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puducherry.
        /// </summary>
        public static string Puducherry {
            get {
                return ResourceManager.GetString("Puducherry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulses.
        /// </summary>
        public static string Pulses {
            get {
                return ResourceManager.GetString("Pulses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pumpkin.
        /// </summary>
        public static string Pumpkin {
            get {
                return ResourceManager.GetString("Pumpkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punjab.
        /// </summary>
        public static string Punjab {
            get {
                return ResourceManager.GetString("Punjab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QTL.
        /// </summary>
        public static string QTL {
            get {
                return ResourceManager.GetString("QTL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QTL/Ha.
        /// </summary>
        public static string QTLHa {
            get {
                return ResourceManager.GetString("QTLHa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rabi.
        /// </summary>
        public static string Rabi {
            get {
                return ResourceManager.GetString("Rabi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ragi.
        /// </summary>
        public static string Ragi {
            get {
                return ResourceManager.GetString("Ragi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rajasthan.
        /// </summary>
        public static string Rajasthan {
            get {
                return ResourceManager.GetString("Rajasthan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rape seed.
        /// </summary>
        public static string Rape_seed {
            get {
                return ResourceManager.GetString("Rape seed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw.
        /// </summary>
        public static string Raw {
            get {
                return ResourceManager.GetString("Raw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relative.
        /// </summary>
        public static string Relative {
            get {
                return ResourceManager.GetString("Relative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request for license.
        /// </summary>
        public static string Request {
            get {
                return ResourceManager.GetString("Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Period.
        /// </summary>
        public static string Return_Period {
            get {
                return ResourceManager.GetString("Return Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        public static string Russian {
            get {
                return ResourceManager.GetString("Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safflower Seeds.
        /// </summary>
        public static string Safflower_Seeds {
            get {
                return ResourceManager.GetString("Safflower Seeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sapota.
        /// </summary>
        public static string Sapota {
            get {
                return ResourceManager.GetString("Sapota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sesame Seeds.
        /// </summary>
        public static string Sesame_Seeds {
            get {
                return ResourceManager.GetString("Sesame Seeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sigma.
        /// </summary>
        public static string Sigma {
            get {
                return ResourceManager.GetString("Sigma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sikkim.
        /// </summary>
        public static string Sikkim {
            get {
                return ResourceManager.GetString("Sikkim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soyabean.
        /// </summary>
        public static string Soyabean {
            get {
                return ResourceManager.GetString("Soyabean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spices.
        /// </summary>
        public static string Spices {
            get {
                return ResourceManager.GetString("Spices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Straight.
        /// </summary>
        public static string Straight {
            get {
                return ResourceManager.GetString("Straight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sugar Cane.
        /// </summary>
        public static string Sugar_Cane {
            get {
                return ResourceManager.GetString("Sugar Cane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum.
        /// </summary>
        public static string Sum {
            get {
                return ResourceManager.GetString("Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunflower.
        /// </summary>
        public static string Sunflower {
            get {
                return ResourceManager.GetString("Sunflower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sweet Potato.
        /// </summary>
        public static string Sweet_Potato {
            get {
                return ResourceManager.GetString("Sweet Potato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamil Nadu.
        /// </summary>
        public static string Tamil_Nadu {
            get {
                return ResourceManager.GetString("Tamil Nadu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tapioca.
        /// </summary>
        public static string Tapioca {
            get {
                return ResourceManager.GetString("Tapioca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taramira.
        /// </summary>
        public static string Taramira {
            get {
                return ResourceManager.GetString("Taramira", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tea.
        /// </summary>
        public static string Tea {
            get {
                return ResourceManager.GetString("Tea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Til.
        /// </summary>
        public static string Til {
            get {
                return ResourceManager.GetString("Til", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to modified National Agricultural Insurance Scheme (mNAIS).
        /// </summary>
        public static string TitleProduct {
            get {
                return ResourceManager.GetString("TitleProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tobacco.
        /// </summary>
        public static string Tobacco {
            get {
                return ResourceManager.GetString("Tobacco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomato.
        /// </summary>
        public static string Tomato {
            get {
                return ResourceManager.GetString("Tomato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ton.
        /// </summary>
        public static string Ton {
            get {
                return ResourceManager.GetString("Ton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ton/Ha.
        /// </summary>
        public static string TonHa {
            get {
                return ResourceManager.GetString("TonHa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tripura.
        /// </summary>
        public static string Tripura {
            get {
                return ResourceManager.GetString("Tripura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turmeric.
        /// </summary>
        public static string Turmeric {
            get {
                return ResourceManager.GetString("Turmeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2000.
        /// </summary>
        public static string TwoThousand {
            get {
                return ResourceManager.GetString("TwoThousand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urad.
        /// </summary>
        public static string Urad {
            get {
                return ResourceManager.GetString("Urad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Specified.
        /// </summary>
        public static string User_Specified {
            get {
                return ResourceManager.GetString("User Specified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uttar Pradesh.
        /// </summary>
        public static string Uttar_Pradesh {
            get {
                return ResourceManager.GetString("Uttar Pradesh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uttarakhand.
        /// </summary>
        public static string Uttarakhand {
            get {
                return ResourceManager.GetString("Uttarakhand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vegetables.
        /// </summary>
        public static string Vegetables {
            get {
                return ResourceManager.GetString("Vegetables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to West Bengal.
        /// </summary>
        public static string West_Bengal {
            get {
                return ResourceManager.GetString("West Bengal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wheat.
        /// </summary>
        public static string Wheat {
            get {
                return ResourceManager.GetString("Wheat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yield.
        /// </summary>
        public static string Yield {
            get {
                return ResourceManager.GetString("Yield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yield Correlation.
        /// </summary>
        public static string Yield_Correlation {
            get {
                return ResourceManager.GetString("Yield Correlation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yield Graphs.
        /// </summary>
        public static string Yield_Graphs {
            get {
                return ResourceManager.GetString("Yield Graphs", resourceCulture);
            }
        }
    }
}
